export const teamAbbreviations = {
    // leagues
    "nfl": "NFL",
    "nba": "NBA",
    "mlb": "MLB",
    "college-football": "CFB",
    "mens-college-basketball": "CBB-M",
    "womens-college-basketball": "CBB-W",

    // NFL
    "Kansas City Chiefs": "KC Chiefs",
    "Jacksonville Jaguars": "JAX Jaguars",
    "New England Patriots": "NE Patriots",
    "Dallas Cowboys": "DAL Cowboys",
    "Los Angeles Rams": "LA Rams",
    "New York Giants": "NY Giants",
    "Washington Commanders": "WAS Commanders",
    "San Francisco 49ers": "SF 49ers",
    "Tampa Bay Buccaneers": "TB Buccaneers",
    "Indianapolis Colts": "IND Colts",
    "Philadelphia Eagles": "PHI Eagles",
    "Cleveland Browns": "CLE Browns",
    "Miami Dolphins": "MIA Dolphins",
    "Seattle Seahawks": "SEA Seahawks",
    "Minnesota Vikings": "MIN Vikings",
    "Buffalo Bills": "BUF Bills",
    "Green Bay Packers": "GB Packers",
    "Pittsburgh Steelers": "PIT Steelers",
    "Arizona Cardinals": "ARI Cardinals",
    "Los Angeles Chargers": "LA Chargers",
    "New York Jets": "NY Jets",
    "Baltimore Ravens": "BAL Ravens",
    "Cincinnati Bengals": "CIN Bengals",
    "Chicago Bears": "CHI Bears",
    "Detroit Lions": "DET Lions",
    "Tennessee Titans": "TEN Titans",
    "New Orleans Saints": "NO Saints",
    "Atlanta Falcons": "ATL Falcons",
    "Houston Texans": "HOU Texans",
    "Carolina Panthers": "CAR Panthers",
    "Denver Broncos": "DEN Broncos",
    "Las Vegas Raiders": "LV Raiders", 
    
    // NBA
    "Los Angeles Lakers": "LA Lakers",
    "Golden State Warriors": "GS Warriors",
    "Brooklyn Nets": "BKN Nets",
    "Milwaukee Bucks": "MIL Bucks",
    "Boston Celtics": "BOS Celtics",
    "Chicago Bulls": "CHI Bulls",
    "Miami Heat": "MIA Heat",
    "Toronto Raptors": "TOR Raptors",
    "Philadelphia 76ers": "PHI 76ers",
    "Dallas Mavericks": "DAL Mavericks",
    "Phoenix Suns": "PHX Suns",
    "Denver Nuggets": "DEN Nuggets",
    "Utah Jazz": "UTA Jazz",
    "Houston Rockets": "HOU Rockets",
    "Cleveland Cavaliers": "CLE Cavaliers",
    "New York Knicks": "NY Knicks",
    "San Antonio Spurs": "SA Spurs",
    "Portland Trail Blazers": "POR Trail Blazers",
    "Orlando Magic": "ORL Magic",
    "Indiana Pacers": "IND Pacers",
    "Washington Wizards": "WAS Wizards",
    "Memphis Grizzlies": "MEM Grizzlies",
    "Charlotte Hornets": "CHA Hornets",
    "Sacramento Kings": "SAC Kings",
    "New Orleans Pelicans": "NO Pelicans",
    "Oklahoma City Thunder": "OKC Thunder",
    "Atlanta Hawks": "ATL Hawks",
    "Minnesota Timberwolves": "MIN Timberwolves",
    "Detroit Pistons": "DET Pistons",

    // MLB
    "Athletics": "Athletics",
    "Baltimore Orioles": "BAL Orioles",
    "Boston Red Sox": "BOS Red Sox",
    "Chicago White Sox": "CHI White Sox",
    "Cleveland Guardians": "CLE Guardians",
    "Detroit Tigers": "DET Tigers",
    "Houston Astros": "HOU Astros",
    "Kansas City Royals": "KC Royals",
    "Los Angeles Angels": "LA Angels",
    "Minnesota Twins": "MIN Twins",
    "New York Yankees": "NY Yankees",
    "Seattle Mariners": "SEA Mariners",
    "Tampa Bay Rays": "TB Rays",
    "Texas Rangers": "TX Rangers",
    "Toronto Blue Jays": "TOR Blue Jays",
    "Arizona Diamondbacks": "ARI Diamondbacks",
    "Atlanta Braves": "ATL Braves",
    "Chicago Cubs": "CHI Cubs",
    "Cincinnati Reds": "CIN Reds",
    "Colorado Rockies": "COL Rockies",
    "Los Angeles Dodgers": "LA Dodgers",
    "Miami Marlins": "MIA Marlins",
    "Milwaukee Brewers": "MIL Brewers",
    "New York Mets": "NY Mets",
    "Philadelphia Phillies": "PHI Phillies",
    "Pittsburgh Pirates": "PIT Pirates",
    "San Diego Padres": "SD Padres",
    "San Francisco Giants": "SF Giants",
    "St. Louis Cardinals": "STL Cardinals",
    "Washington Nationals": "WAS Nationals",

    // Soccer
    // england
    "Aston Villa": "Aston Villa",
    "Brighton & Hove Albion": "Brighton",
    "Nottingham Forest": "Nottingham Forest",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",

    // NCAA
    // ACC
    "Boston College Eagles": "Boston College",
    "California Golden Bears": "California",
    "Clemson Tigers": "Clemson",
    "Duke Blue Devils": "Duke",
    "Florida State Seminoles": "Florida State",
    "Georgia Tech Yellow Jackets": "Georgia Tech",
    "Louisville Cardinals": "Louisville",
    "Miami Hurricanes": "Miami",
    "NC State Wolfpack": "NC State",
    "North Carolina Tar Heels": "North Carolina",
    "Notre Dame Fighting Irish": "Notre Dame",
    "Pittsburgh Panthers": "Pittsburgh",
    "SMU Mustangs": "SMU",
    "Stanford Cardinal": "Stanford",
    "Syracuse Orange": "Syracuse",
    "Virginia Cavaliers": "Virginia",
    "Virginia Tech Hokies": "Virginia Tech",
    "Wake Forest Demon Deacons": "Wake Forest",

    // ASUN
    "Austin Peay Governors": "Austin Peay",
    "Bellarmine Knights": "Bellarmine",
    "Central Arkansas Bears": "Central Arkansas",
    "Eastern Kentucky Colonels": "Eastern Kentucky",
    "Florida Gulf Coast Eagles": "Florida Gulf Coast",
    "Jacksonville Dolphins": "Jacksonville",
    "Lipscomb Bisons": "Lipscomb",
    "North Alabama Lions": "North Alabama",
    "North Florida Ospreys": "North Florida",
    "Queens University Royals": "Queens University",
    "Stetson Hatters": "Stetson",
    "West Georgia Wolves": "West Georgia",

    // American East
    "Binghamton Bearcats": "Binghamton",
    "Bryanton Bulldogs": "Bryant",
    "Maine Black Bears": "Maine",
    "NJIT Highlanders": "NJIT",
    "New Hampshire Wildcats": "New Hampshire",
    "UAlbany Great Danes": "Albany",
    "UMBC Retrievers": "UMBC",
    "UMass Lowell River Hawks": "UMass Lowell",
    "Vermont Catamounts": "Vermont",

    // American
    "Charlotte 49ers": "Charlotte",
    "East Carolina Pirates": "East Carolina",
    "Florida Atlantic Owls": "Florida Atlantic",
    "North Texas Mean Green": "North Texas",
    "Memphis Tigers": "Memphis",
    "Rice Owls": "Rice",
    "South Florida Bulls": "South Florida",
    "Temple Owls": "Temple",
    "Tulane Green Wave": "Tulane",
    "Tulsa Golden Hurricane": "Tulsa",
    "Wichita State Shockers": "Wichita State",
    "UAB Blazers": "UAB",
    "UTSA Roadrunners": "UTSA",

    // A10
    "Davidson Wildcats": "Davidson",
    "Dayton Flyers": "Dayton",
    "Duquesne Dukes": "Duquesne",
    "Fordham Rams": "Fordham",
    "George Mason Patriots": "George Mason",
    "George Washington Revolutionaries": "George Washington",
    "La Salle Explorers": "La Salle",
    "Loyola Chicago Ramblers": "Loyola Chicago",
    "Rhode Island Rams": "Rhode Island",
    "Richmond Spiders": "Richmond",
    "Saint Joseph's Hawks": "Saint Joseph's",
    "Saint Louis Billikens": "Saint Louis",
    "St. Bonaventure Bonnies": "St. Bonaventure",
    "VCU Rams": "VCU",

    // Big 12
    "Arizona State Sun Devils": "Arizona State",
    "Arizona Wildcats": "Arizona",
    "BYU Cougars": "BYU",
    "Baylor Bears": "Baylor",
    "Cincinnati Bearcats": "Cincinnati",
    "Colorado Buffaloes": "Colorado",
    "Houston Cougars": "Houston",
    "Iowa State Cyclones": "Iowa State",
    "Kansas Jayhawks": "Kansas",
    "Kansas State Wildcats": "Kansas State",
    "Oklahoma State Cowboys": "Oklahoma State",
    "TCU Horned Frogs": "TCU",
    "Texas Tech Red Raiders": "Texas Tech",
    "UCF Knights": "UCF",
    "Utah Utes": "Utah",
    "West Virginia Mountaineers": "West Virginia",

    // Big East
    "Butler Bulldogs": "Butler",
    "Creighton Bluejays": "Creighton",
    "DePaul Blue Demons": "DePaul",
    "Georgetown Hoyas": "Georgetown",
    "Marquette Golden Eagles": "Marquette",
    "Providece Friars": "Providence",
    "Seton Hall Pirates": "Seton Hall",
    "St. John's Red Storm": "St. John's",
    "UConn Huskies": "UConn",
    "Villanova Wildcats": "Villanova",
    "Xavier Musketeers": "Xavier",

    // Big Sky
    "Eastern Washington Eagles": "Eastern Washington",
    "Idaho Vandals": "Idaho",
    "Idaho State Bengals": "Idaho State",
    "Montana Grizzlies": "Montana",
    "Montana State Bobcats": "Montana State",
    "Northern Arizona Lumberjacks": "Northern Arizona",
    "Northern Colorado Bears": "Northern Colorado",
    "Portland State Vikings": "Portland State",
    "Sacramento State Hornets": "Sacramento State",
    "Weber State Wildcats": "Weber State",

    // Big South
    "Charleston Southern Buccaneers": "Charleston Southern",
    "Gardner-Webb Runnin' Bulldogs": "Gardner-Webb",
    "High Point Panthers": "High Point",
    "Longwood Lancers": "Longwood",
    "Presbyterian Blue Hose": "Presbyterian",
    "Radford Highlanders": "Radford",
    "South Carolina Upstate Spartans": "USC Upstate",
    "UNC Asheville Bulldogs": "UNC Asheville",
    "Winthrop Eagles": "Winthrop",

    // Big Ten
    "Illinois Fighting Illini": "Illinois",
    "Indiana Hoosiers": "Indiana",
    "Iowa Hawkeyes": "Iowa",
    "Maryland Terrapins": "Maryland",
    "Michigan Wolverines": "Michigan",
    "Michigan State Spartans": "Michigan State",
    "Minnesota Golden Gophers": "Minnesota",
    "Nebraska Cornhuskers": "Nebraska",
    "Northwestern Wildcats": "Northwestern",
    "Ohio State Buckeyes": "Ohio State",
    "Oregon Ducks": "Oregon",
    "Penn State Nittany Lions": "Penn State",
    "Purdue Boilermakers": "Purdue",
    "Rutgers Scarlet Knights": "Rutgers",
    "UCLA Bruins": "UCLA",
    "USC Trojans": "USC",
    "Washington Huskies": "Washington",
    "Wisconsin Badgers": "Wisconsin",

    // Big West
    "Cal Poly Mustangs": "Cal Poly",
    "Cal State Bakersfield Roadrunners": "Cal State Bakersfield",
    "Cal State Fullerton Titans": "Cal State Fullerton",
    "Cal State Northridge Matadors": "Cal State Northridge",
    "Hawai'i Rainbow Warriors": "Hawaii",
    "Long Beach State Beach": "Long Beach State",
    "UC Davis Aggies": "UC Davis",
    "UC Irvine Anteaters": "UC Irvine",
    "UC Riverside Highlanders": "UC Riverside",
    "UC San Diego Tritons": "UC San Diego",
    "UC Santa Barbara Gauchos": "UC Santa Barbara",


    // Coastal
    "Campbell Fighting Camels": "Campbell",
    "Charleston Cougars": "Charleston",
    "Drexel Dragons": "Drexel",
    "Elon Phoenix": "Elon",
    "Hampton Pirates": "Hampton",
    "Hofstra Pride": "Hofstra",
    "Monmouth Hawks": "Monmouth",
    "North Carolina A&T Aggies": "North Carolina A&T",
    "Northeastern Huskies": "Northeastern",
    "Stony Brook Seawolves": "Stony Brook",
    "Towson Tigers": "Towson",
    "UNC Wilmington Seahawks": "UNC Wilmington",
    "William & Mary Tribe": "William & Mary",

    // Conference USA
    "Delaware Blue Hens": "Delaware",
    "Florida International Panthers": "Florida International",
    "Jacksonville State Gamecocks": "Jacksonville State",
    "Kennesaw State Owls": "Kennesaw State",
    "Liberty Flames": "Liberty",
    "Louisiana Tech Bulldogs": "Louisiana Tech",
    "Middle Tennessee Blue Raiders": "Middle Tennessee",
    "Missouri State Bears": "Missouri State",
    "New Mexico State Aggies": "New Mexico State",
    "Sam Houston Bearkats": "Sam Houston",
    "UTEP Miners": "UTEP",
    "Western Kentucky Hilltoppers": "Western Kentucky",

    // Horizon
    "Cleveland State Vikings": "Cleveland State",
    "Detroit Mercy Titans": "Detroit Mercy",
    "Green Bay Phoenix": "Green Bay",
    "IU Indianapolis Jaguars": "IU Indianapolis",
    "Milwaukee Panthers": "Milwaukee",
    "Northern Kentucky Norse": "Northern Kentucky",
    "Oakland Golden Grizzlies": "Oakland",
    "Purdue Fort Wayne Mastodons": "Purdue Fort Wayne",
    "Robert Morris Colonials": "Robert Morris",
    "Wright State Raiders": "Wright State",
    "Youngstown State Penguins": "Youngstown State",

    // Ivy
    "Brown Bears": "Brown",
    "Columbia Lions": "Columbia",
    "Cornell Big Red": "Cornell",
    "Dartmouth Big Green": "Dartmouth",
    "Harvard Crimson": "Harvard",
    "Pennsylvania Quakers": "Penn",
    "Princeton Tigers": "Princeton",
    "Yale Bulldogs": "Yale",

    // MAAC
    "Canisius Golden Griffins": "Canisius",
    "Fairfield Stags": "Fairfield",
    "Iona Gaels": "Iona",
    "Manhattan Jaspers": "Manhattan",
    "Marist Red Foxes": "Marist",
    "Merrimack Warriors": "Merrimack",
    "Mount St. Mary's Mountaineers": "Mount St. Mary's",
    "Niagara Purple Eagles": "Niagara",
    "Quinnipiac Bobcats": "Quinnipiac",
    "Rider Broncs": "Rider",
    "Sacred Heart Pioneers": "Sacred Heart",
    "Saint Peter's Peacocks": "Saint Peter's",
    "Siena Saints": "Siena",

    // MAC
    "Akron Zips": "Akron",
    "Ball State Cardinals": "Ball State",
    "Bowling Green Falcons": "Bowling Green",
    "Buffalo Bulls": "Buffalo",
    "Central Michigan Chippewas": "Central Michigan",
    "Eastern Michigan Eagles": "Eastern Michigan",
    "Kent State Golden Flashes": "Kent State",
    "Massachusetts Minutemen": "UMass",
    "Miami (OH) RedHawks": "Miami (OH)",
    "Northern Illinois Huskies": "Northern Illinois",
    "Ohio Bobcats": "Ohio",
    "Toledo Rockets": "Toledo",
    "Western Michigan Broncos": "Western Michigan",

    // MEAC
    "Coppin State Eagles": "Coppin State",
    "Delaware State Hornets": "Delaware State",
    "Howard Bison": "Howard",
    "Maryland Eastern Shore Hawks": "Maryland Eastern Shore",
    "Morgan State Bears": "Morgan State",
    "Norfolk State Spartans": "Norfolk State",
    "North Carolina Central Eagles": "North Carolina Central",
    "South Carolina State Bulldogs": "South Carolina State",

    // Missouri Valley
    "Belmont Bruins": "Belmont",
    "Bradley Braves": "Bradley",
    "Drake Bulldogs": "Drake",
    "Evansville Purple Aces": "Evansville",
    "Illinois State Redbirds": "Illinois State",
    "Indiana State Sycamores": "Indiana State",
    "Murray State Racers": "Murray State",
    "Northern Iowa Panthers": "Northern Iowa",
    "Southern Illinois Salukis": "Southern Illinois",
    "UIC Flames": "UIC",
    "Valparaiso Beacons": "Valparaiso",

    // Mountain West
    "Air Force Falcons": "Air Force",
    "Boise State Broncos": "Boise State",
    "Colorado State Rams": "Colorado State",
    "Fresno State Bulldogs": "Fresno State",
    "Grand Canyon Lopes": "Grand Canyon",
    "Nevada Wolf Pack": "Nevada",
    "New Mexico Lobos": "New Mexico",
    "San Diego State Aztecs": "San Diego State",
    "San José State Spartans": "San José State",
    "UNLV Rebels": "UNLV",
    "Utah State Aggies": "Utah State",
    "Wyoming Cowboys": "Wyoming",

    // NEC
    "Central Connecticut Blue Devils": "Central Connecticut",
    "Chicago State Cougars": "Chicago State",
    "Fairleigh Dickinson Knights": "Fairleigh Dickinson",
    "Le Moyne Dolphins": "Le Moyne",
    "Long Island University Sharks": "Long Island",
    "Mercyhurst Lakers": "Mercyhurst",
    "New Haven Chargers": "New Haven",
    "Saint Francis Red Flash": "Saint Francis",
    "Stonehill Skyhawks": "Stonehill",
    "Wagner Seahawks": "Wagner",

    // Ohio Valley
    "Eastern Illinois Panthers": "Eastern Illinois",
    "Lindenwood Lions": "Lindenwood",
    "Little Rock Trojans": "Little Rock",
    "Morehead State Eagles": "Morehead State",
    "SIU Edwardsville Cougars": "SIU Edwardsville",
    "Southeast Missouri State Redhawks": "Southeast Missouri State",
    "Southern Indiana Screaming Eagles": "Southern Indiana",
    "Tennessee State Tigers": "Tennessee State",
    "Tennessee Tech Golden Eagles": "Tennessee Tech",
    "UT Martin Skyhawks": "UT Martin",
    "Western Illinois Leathernecks": "Western Illinois",

    // Patriot League
    "American University Eagles": "American University",
    "Army Black Knights": "Army",
    "Boston University Terriers": "Boston University",
    "Bucknell Bison": "Bucknell",
    "Colgate Raiders": "Colgate",
    "Holy Cross Crusaders": "Holy Cross",
    "Lafayette Leopards": "Lafayette",
    "Lehigh Mountain Hawks": "Lehigh",
    "Loyola Maryland Greyhounds": "Loyola Maryland",
    "Navy Midshipmen": "Navy",

    // SEC
    "Alabama Crimson Tide": "Alabama",
    "Arkansas Razorbacks": "Arkansas",
    "Auburn Tigers": "Auburn",
    "Florida Gators": "Florida",
    "Georgia Bulldogs": "Georgia",
    "Kentucky Wildcats": "Kentucky",
    "LSU Tigers": "LSU",
    "Mississippi State Bulldogs": "Mississippi State",
    "Missouri Tigers": "Missouri",
    "Oklahoma Sooners": "Oklahoma",
    "Ole Miss Rebels": "Ole Miss",
    "South Carolina Gamecocks": "South Carolina",
    "Tennessee Volunteers": "Tennessee",
    "Texas Longhorns": "Texas",
    "Texas A&M Aggies": "Texas A&M",
    "Vanderbilt Commodores": "Vanderbilt",

    // Southern
    "Chattanooga Mocs": "Chattanooga",
    "East Tennessee State Buccaneers": "East Tennessee State",
    "Furman Paladins": "Furman",
    "Mercer Bears": "Mercer",
    "Samford Bulldogs": "Samford",
    "The Citadel Bulldogs": "The Citadel",
    "UNC Greensboro Spartans": "UNC Greensboro",
    "VMI Keydets": "VMI",
    "Western Carolina Catamounts": "Western Carolina",
    "Wofford Terriers": "Wofford",

    // Southland
    "East Texas A&M Lions": "East Texas A&M",
    "Houston Christian Huskies": "Houston Christian",
    "Incarnate Word Cardinals": "Incarnate Word",
    "Lamar Cardinals": "Lamar",
    "McNeese Cowboys": "McNeese",
    "New Orleans Privateers": "New Orleans",
    "Nicholls Colonels": "Nicholls",
    "Northwestern State Demons": "Northwestern State",
    "SE Louisiana Lions": "SE Louisiana",
    "Stephen F. Austin Lumberjacks": "Stephen F. Austin",
    "Texas A&M-Corpus Christi Islanders": "Texas A&M-Corpus Christi",
    "UT Rio Grande Valley Vaqueros": "UT RGV",

    // Summit
    "Denver Pioneers": "Denver",
    "Kansas City Roos": "Kansas City",
    "North Dakota Fighting Hawks": "North Dakota",
    "North Dakota State Bison": "North Dakota State",
    "Omaha Mavericks": "Omaha",
    "Oral Roberts Golden Eagles": "Oral Roberts",
    "South Dakota Coyotes": "South Dakota",
    "South Dakota State Jackrabbits": "South Dakota State",
    "St. Thomas-Minnesota Tommies": "St. Thomas",
    

    // Sun Belt
    "App State Mountaineers": "Appalachian State",
    "Arkansas State Red Wolves": "Arkansas State",
    "Coastal Carolina Chanticleers": "Coastal Carolina",
    "Georgia Southern Eagles": "Georgia Southern",
    "Georgia State Panthers": "Georgia State",
    "James Madison Dukes": "James Madison",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "UL Monroe Warhawks": "UL Monroe",
    "Marshall Thundering Herd": "Marshall",
    "Old Dominion Monarchs": "Old Dominion",
    "South Alabama Jaguars": "South Alabama",
    "Southern Miss Golden Eagles": "Southern Miss",
    "Texas State Bobcats": "Texas State",
    "Troy Trojans": "Troy",

    // SWAC
    "Alabama A&M Bulldogs": "Alabama A&M",
    "Alabama State Hornets": "Alabama State",
    "Alcorn State Braves": "Alcorn State",
    "Arkansas-Pine Bluff Golden Lions": "Arkansas-Pine Bluff",
    "Bethune-Cookman Wildcats": "Bethune-Cookman",
    "Florida A&M Rattlers": "Florida A&M",
    "Grambling State Tigers": "Grambling State",
    "Jackson State Tigers": "Jackson State",
    "Mississippi Valley State Delta Devils": "Mississippi Valley State",
    "Prairie View A&M Panthers": "Prairie View A&M",
    "Southern Jaguars": "Southern",
    "Texas Southern Tigers": "Texas Southern",

    // WAC
    "Abilene Christian Wildcats": "Abilene Christian",
    "California Baptist Lancers": "California Baptist",
    "Southern Utah Thunderbirds": "Southern Utah",
    "Tarleton State Texans": "Tarleton State",
    "UT Arlington Mavericks": "UT Arlington",
    "Utah Tech Trailblazers": "Utah Tech",
    "Utah Valley Wolverines": "Utah Valley",

    // WCC
    "Gonzaga Bulldogs": "Gonzaga",
    "Loyola Marymount Lions": "Loyola Marymount",
    "Oregon State Beavers": "Oregon State",
    "Pacific Tigers": "Pacific",
    "Pepperdine Waves": "Pepperdine",
    "Portland Pilots": "Portland",
    "San Francisco Dons": "San Francisco",
    "Santa Clara Broncos": "Santa Clara",
    "San Diego Toreros": "San Diego",
    "Saint Mary's Gaels": "Saint Mary's",
    "Seattle U Redhawks": "Seattle U",
    "Washington State Cougars": "Washington State",
};

export const teamLogos = {
    // NFL
    "Arizona Cardinals": "src/assets/teamLogos/NFL/ARI_Cardinals.png",
    "Atlanta Falcons": "src/assets/teamLogos/NFL/ATL_Falcons.png",
    "Baltimore Ravens": "src/assets/teamLogos/NFL/BAL_Ravens.png",
    "Buffalo Bills": "src/assets/teamLogos/NFL/BUF_Bills.png",
    "Carolina Panthers": "src/assets/teamLogos/NFL/CAR_Panthers.png",
    "Chicago Bears": "src/assets/teamLogos/NFL/CHI_Bears.png",
    "Cincinnati Bengals": "src/assets/teamLogos/NFL/CIN_Bengals.png",
    "Cleveland Browns": "src/assets/teamLogos/NFL/CLE_Browns.png",
    "Dallas Cowboys": "src/assets/teamLogos/NFL/DAL_Cowboys.png",
    "Denver Broncos": "src/assets/teamLogos/NFL/DEN_Broncos.png",
    "Detroit Lions": "src/assets/teamLogos/NFL/DET_Lions.png",
    "Green Bay Packers": "src/assets/teamLogos/NFL/GB_Packers.png",
    "Houston Texans": "src/assets/teamLogos/NFL/HOU_Texans.png",
    "Indianapolis Colts": "src/assets/teamLogos/NFL/IND_Colts.png",
    "Jacksonville Jaguars": "src/assets/teamLogos/NFL/JAX_Jaguars.png",
    "Kansas City Chiefs": "src/assets/teamLogos/NFL/KC_Chiefs.png",
    "Las Vegas Raiders": "src/assets/teamLogos/NFL/LV_Raiders.png",
    "Los Angeles Chargers": "src/assets/teamLogos/NFL/LA_Chargers.png",
    "Los Angeles Rams": "src/assets/teamLogos/NFL/LA_Rams.png",
    "Miami Dolphins": "src/assets/teamLogos/NFL/MIA_Dolphins.png",
    "Minnesota Vikings": "src/assets/teamLogos/NFL/MIN_Vikings.png",
    "New England Patriots": "src/assets/teamLogos/NFL/NE_Patriots.png",
    "New Orleans Saints": "src/assets/teamLogos/NFL/NO_Saints.png",
    "New York Giants": "src/assets/teamLogos/NFL/NY_Giants.png",
    "New York Jets": "src/assets/teamLogos/NFL/NY_Jets.png",
    "Philadelphia Eagles": "src/assets/teamLogos/NFL/PHI_Eagles.png",
    "Pittsburgh Steelers": "src/assets/teamLogos/NFL/PIT_Steelers.png",
    "San Francisco 49ers": "src/assets/teamLogos/NFL/SF_49ers.png",
    "Seattle Seahawks": "src/assets/teamLogos/NFL/SEA_Seahawks.png",
    "Tampa Bay Buccaneers": "src/assets/teamLogos/NFL/TB_Buccaneers.png",
    "Tennessee Titans": "src/assets/teamLogos/NFL/TEN_Titans.png",
    "Washington Commanders": "src/assets/teamLogos/NFL/WAS_Commanders.png",

    // NBA
    "Atlanta Hawks": "src/assets/teamLogos/NBA/ATL_Hawks.png",
    "Boston Celtics": "src/assets/teamLogos/NBA/BOS_Celtics.png",
    "Brooklyn Nets": "src/assets/teamLogos/NBA/BKN_Nets.png",
    "Charlotte Hornets": "src/assets/teamLogos/NBA/CHA_Hornets.png",
    "Chicago Bulls": "src/assets/teamLogos/NBA/CHI_Bulls.png",
    "Cleveland Cavaliers": "src/assets/teamLogos/NBA/CLE_Cavaliers.png",
    "Dallas Mavericks": "src/assets/teamLogos/NBA/DAL_Mavericks.png",
    "Denver Nuggets": "src/assets/teamLogos/NBA/DEN_Nuggets.png",
    "Detroit Pistons": "src/assets/teamLogos/NBA/DET_Pistons.png",
    "Golden State Warriors": "src/assets/teamLogos/NBA/GS_Warriors.png",
    "Houston Rockets": "src/assets/teamLogos/NBA/HOU_Rockets.png",
    "Indiana Pacers": "src/assets/teamLogos/NBA/IND_Pacers.png",
    "Los Angeles Clippers": "src/assets/teamLogos/NBA/LA_Clippers.png",
    "LA Clippers": "src/assets/teamLogos/NBA/LA_Clippers.png",
    "Los Angeles Lakers": "src/assets/teamLogos/NBA/LA_Lakers.png",
    "Memphis Grizzlies": "src/assets/teamLogos/NBA/MEM_Grizzlies.png",
    "Miami Heat": "src/assets/teamLogos/NBA/MIA_Heat.png",
    "Milwaukee Bucks": "src/assets/teamLogos/NBA/MIL_Bucks.png",
    "Minnesota Timberwolves": "src/assets/teamLogos/NBA/MIN_Timberwolves.png",
    "New Orleans Pelicans": "src/assets/teamLogos/NBA/NO_Pelicans.png",
    "New York Knicks": "src/assets/teamLogos/NBA/NY_Knicks.png",
    "Oklahoma City Thunder": "src/assets/teamLogos/NBA/OKC_Thunder.png",
    "Orlando Magic": "src/assets/teamLogos/NBA/ORL_Magic.png",
    "Philadelphia 76ers": "src/assets/teamLogos/NBA/PHI_76ers.png",
    "Phoenix Suns": "src/assets/teamLogos/NBA/PHX_Suns.png",
    "Portland Trail Blazers": "src/assets/teamLogos/NBA/POR_Trail_Blazers.png",
    "Sacramento Kings": "src/assets/teamLogos/NBA/SAC_Kings.png",
    "San Antonio Spurs": "src/assets/teamLogos/NBA/SA_Spurs.png",
    "Toronto Raptors": "src/assets/teamLogos/NBA/TOR_Raptors.png",
    "Utah Jazz": "src/assets/teamLogos/NBA/UTA_Jazz.png",
    "Washington Wizards": "src/assets/teamLogos/NBA/WAS_Wizards.png",

    // MLB
    "Athletics": "src/assets/teamLogos/MLB/Athletics.png",
    "Baltimore Orioles": "src/assets/teamLogos/MLB/BAL_Orioles.png",
    "Boston Red Sox": "src/assets/teamLogos/MLB/BOS_Red_Sox.png",
    "Chicago White Sox": "src/assets/teamLogos/MLB/CHI_White_Sox.png",
    "Cleveland Guardians": "src/assets/teamLogos/MLB/CLE_Guardians.png",
    "Detroit Tigers": "src/assets/teamLogos/MLB/DET_Tigers.png",
    "Houston Astros": "src/assets/teamLogos/MLB/HOU_Astros.png",
    "Kansas City Royals": "src/assets/teamLogos/MLB/KC_Royals.png",
    "Los Angeles Angels": "src/assets/teamLogos/MLB/LA_Angels.png",
    "Minnesota Twins": "src/assets/teamLogos/MLB/MIN_Twins.png",
    "New York Yankees": "src/assets/teamLogos/MLB/NY_Yankees.png",
    "Seattle Mariners": "src/assets/teamLogos/MLB/SEA_Mariners.png",
    "Tampa Bay Rays": "src/assets/teamLogos/MLB/TB_Rays.png",
    "Texas Rangers": "src/assets/teamLogos/MLB/TX_Rangers.png",
    "Toronto Blue Jays": "src/assets/teamLogos/MLB/TOR_Blue_Jays.png",
    "Arizona Diamondbacks": "src/assets/teamLogos/MLB/ARI_Diamondbacks.png",
    "Atlanta Braves": "src/assets/teamLogos/MLB/ATL_Braves.png",
    "Chicago Cubs": "src/assets/teamLogos/MLB/CHI_Cubs.png",
    "Cincinnati Reds": "src/assets/teamLogos/MLB/CIN_Reds.png",
    "Colorado Rockies": "src/assets/teamLogos/MLB/COL_Rockies.png",
    "Los Angeles Dodgers": "src/assets/teamLogos/MLB/LA_Dodgers.png",
    "Miami Marlins": "src/assets/teamLogos/MLB/MIA_Marlins.png",
    "Milwaukee Brewers": "src/assets/teamLogos/MLB/MIL_Brewers.png",
    "New York Mets": "src/assets/teamLogos/MLB/NY_Mets.png",
    "Philadelphia Phillies": "src/assets/teamLogos/MLB/PHI_Phillies.png",
    "Pittsburgh Pirates": "src/assets/teamLogos/MLB/PIT_Pirates.png",
    "San Diego Padres": "src/assets/teamLogos/MLB/SD_Padres.png",
    "San Francisco Giants": "src/assets/teamLogos/MLB/SF_Giants.png",
    "St. Louis Cardinals": "src/assets/teamLogos/MLB/STL_Cardinals.png",
    "Washington Nationals": "src/assets/teamLogos/MLB/WAS_Nationals.png",

    // Soccer
    // international
    "Benin": "src/assets/teamLogos/Soccer/International/Benin.png",
    "Cameroon": "src/assets/teamLogos/Soccer/International/Cameroon.png",
    "Egypt": "src/assets/teamLogos/Soccer/International/Egypt.png",
    "Mali": "src/assets/teamLogos/Soccer/International/Mali.png",
    "Morocco": "src/assets/teamLogos/Soccer/International/Morocco.png",
    "Mozambique": "src/assets/teamLogos/Soccer/International/Mozambique.png",
    "Nigeria": "src/assets/teamLogos/Soccer/International/Nigeria.png",
    "Senegal": "src/assets/teamLogos/Soccer/International/Senegal.png",
    "South Africa": "src/assets/teamLogos/Soccer/International/South_Africa.png",
    "Sudan": "src/assets/teamLogos/Soccer/International/Sudan.png",
    "Tanzania": "src/assets/teamLogos/Soccer/International/Tanzania.png",
    "Tunisia": "src/assets/teamLogos/Soccer/International/Tunisia.png",

    // england
    "AFC Bournemouth": "src/assets/teamLogos/Soccer/ENG/AFC_Bournemouth.png",
    "Arsenal": "src/assets/teamLogos/Soccer/ENG/Arsenal.png",
    "Aston Villa": "src/assets/teamLogos/Soccer/ENG/Aston_Villa.png",
    "Birmingham City": "src/assets/teamLogos/Soccer/ENG/Birmingham_City.png",
    "Blackburn Rovers": "src/assets/teamLogos/Soccer/ENG/Blackburn_Rovers.png",
    "Brentford": "src/assets/teamLogos/Soccer/ENG/Brentford.png",
    "Brighton & Hove Albion": "src/assets/teamLogos/Soccer/ENG/Brighton_and_Hove_Albion.png",
    "Bristol City": "src/assets/teamLogos/Soccer/ENG/Bristol_City.png",
    "Burnley": "src/assets/teamLogos/Soccer/ENG/Burnley.png",
    "Charlton Athletic": "src/assets/teamLogos/Soccer/ENG/Charlton_Athletic.png",
    "Chelsea": "src/assets/teamLogos/Soccer/ENG/Chelsea.png",
    "Coventry City": "src/assets/teamLogos/Soccer/ENG/Coventry_City.png",
    "Crystal Palace": "src/assets/teamLogos/Soccer/ENG/Crystal_Palace.png",
    "Derby County": "src/assets/teamLogos/Soccer/ENG/Derby_County.png",
    "Everton": "src/assets/teamLogos/Soccer/ENG/Everton.png",
    "Fulham": "src/assets/teamLogos/Soccer/ENG/Fulham.png",
    "Hull City": "src/assets/teamLogos/Soccer/ENG/Hull_City.png",
    "Ipswich Town": "src/assets/teamLogos/Soccer/ENG/Ipswich_Town.png",
    "Leeds United": "src/assets/teamLogos/Soccer/ENG/Leeds_United.png",
    "Leicester City": "src/assets/teamLogos/Soccer/ENG/Leicester_City.png",
    "Liverpool": "src/assets/teamLogos/Soccer/ENG/Liverpool.png",
    "Manchester City": "src/assets/teamLogos/Soccer/ENG/Manchester_City.png",
    "Manchester United": "src/assets/teamLogos/Soccer/ENG/Manchester_United.png",
    "Middlesbrough": "src/assets/teamLogos/Soccer/ENG/Middlesbrough.png",
    "Millwall": "src/assets/teamLogos/Soccer/ENG/Millwall.png",
    "Newcastle United": "src/assets/teamLogos/Soccer/ENG/Newcastle_United.png",
    'Norwich City': "src/assets/teamLogos/Soccer/ENG/Norwich_City.png",
    "Nottingham Forest": "src/assets/teamLogos/Soccer/ENG/Nottingham_Forest.png",
    "Oxford United": "src/assets/teamLogos/Soccer/ENG/Oxford_United.png",
    "Portsmouth": "src/assets/teamLogos/Soccer/ENG/Portsmouth.png",
    "Preston North End": "src/assets/teamLogos/Soccer/ENG/Preston_North_End.png",
    "Queens Park Rangers": "src/assets/teamLogos/Soccer/ENG/Queens_Park_Rangers.png",
    "Sheffield United": "src/assets/teamLogos/Soccer/ENG/Sheffield_United.png",
    "Sheffield Wednesday": "src/assets/teamLogos/Soccer/ENG/Sheffield_Wednesday.png",
    "Southampton": "src/assets/teamLogos/Soccer/ENG/Southampton.png",
    "Stoke City": "src/assets/teamLogos/Soccer/ENG/Stoke_City.png",
    "Sunderland": "src/assets/teamLogos/Soccer/ENG/Sunderland.png",
    "Swansea City": "src/assets/teamLogos/Soccer/ENG/Swansea_City.png",
    "Tottenham Hotspur": "src/assets/teamLogos/Soccer/ENG/Tottenham_Hotspur.png",
    "Watford": "src/assets/teamLogos/Soccer/ENG/Watford.png",
    "West Bromwich Albion": "src/assets/teamLogos/Soccer/ENG/West_Bromwich_Albion.png",
    "West Ham United": "src/assets/teamLogos/Soccer/ENG/West_Ham_United.png",
    "Wolverhampton Wanderers": "src/assets/teamLogos/Soccer/ENG/Wolverhampton_Wanderers.png",
    "Wrexham": "src/assets/teamLogos/Soccer/ENG/Wrexham.png",

    // italy
    "AC Milan": "src/assets/teamLogos/Soccer/ITA/AC_Milan.png",
    "AS Roma": "src/assets/teamLogos/Soccer/ITA/AS_Roma.png",
    "Atalanta": "src/assets/teamLogos/Soccer/ITA/Atalanta.png",
    "Como": "src/assets/teamLogos/Soccer/ITA/Como.png",
    "Juventus": "src/assets/teamLogos/Soccer/ITA/Juventus.png",
    "Lecce": "src/assets/teamLogos/Soccer/ITA/Lecce.png",
    "Pisa": "src/assets/teamLogos/Soccer/ITA/Pisa.png",



    // NCAA
    // ACC
    "Boston College Eagles": "src/assets/teamLogos/NCAA/Boston_College_Eagles.png",
    "California Golden Bears": "src/assets/teamLogos/NCAA/California_Golden_Bears.png",
    "Clemson Tigers": "src/assets/teamLogos/NCAA/Clemson_Tigers.png",
    "Duke Blue Devils": "src/assets/teamLogos/NCAA/Duke_Blue_Devils.png",
    "Florida State Seminoles": "src/assets/teamLogos/NCAA/Florida_State_Seminoles.png",
    "Georgia Tech Yellow Jackets": "src/assets/teamLogos/NCAA/Georgia_Tech_Yellow_Jackets.png",
    "Louisville Cardinals": "src/assets/teamLogos/NCAA/Louisville_Cardinals.png",
    "Miami Hurricanes": "src/assets/teamLogos/NCAA/Miami_Hurricanes.png",
    "NC State Wolfpack": "src/assets/teamLogos/NCAA/NC_State_Wolfpack.png",
    "North Carolina Tar Heels": "src/assets/teamLogos/NCAA/North_Carolina_Tar_Heels.png",
    "Notre Dame Fighting Irish": "src/assets/teamLogos/NCAA/Notre_Dame_Fighting_Irish.png",
    "Pittsburgh Panthers": "src/assets/teamLogos/NCAA/Pittsburgh_Panthers.png",
    "SMU Mustangs": "src/assets/teamLogos/NCAA/SMU_Mustangs.png",
    "Stanford Cardinal": "src/assets/teamLogos/NCAA/Stanford_Cardinal.png",
    "Syracuse Orange": "src/assets/teamLogos/NCAA/Syracuse_Orange.png",
    "Virginia Cavaliers": "src/assets/teamLogos/NCAA/Virginia_Cavaliers.png",
    "Virginia Tech Hokies": "src/assets/teamLogos/NCAA/Virginia_Tech_Hokies.png",
    "Wake Forest Demon Deacons": "src/assets/teamLogos/NCAA/Wake_Forest_Demon_Deacons.png",

    // ASUN
    "Austin Peay Governors": "src/assets/teamLogos/NCAA/Austin_Peay_Governors.png",
    "Bellarmine Knights": "src/assets/teamLogos/NCAA/Bellarmine_Knights.png",
    "Central Arkansas Bears": "src/assets/teamLogos/NCAA/Central_Arkansas_Bears.png",
    "Eastern Kentucky Colonels": "src/assets/teamLogos/NCAA/Eastern_Kentucky_Colonels.png",
    "Florida Gulf Coast Eagles": "src/assets/teamLogos/NCAA/Florida_Gulf_Coast_Eagles.png",
    "Jacksonville Dolphins": "src/assets/teamLogos/NCAA/Jacksonville_Dolphins.png",
    "Lipscomb Bisons": "src/assets/teamLogos/NCAA/Lipscomb_Bisons.png",
    "North Alabama Lions": "src/assets/teamLogos/NCAA/North_Alabama_Lions.png",
    "North Florida Ospreys": "src/assets/teamLogos/NCAA/North_Florida_Ospreys.png",
    "Queens University Royals": "src/assets/teamLogos/NCAA/Queens_University_Royals.png",
    "Stetson Hatters": "src/assets/teamLogos/NCAA/Stetson_Hatters.png",
    "West Georgia Wolves": "src/assets/teamLogos/NCAA/West_Georgia_Wolves.png",
    
    // American East
    "Binghamton Bearcats": "src/assets/teamLogos/NCAA/Binghamton_Bearcats.png",
    "Bryanton Bulldogs": "src/assets/teamLogos/NCAA/Bryant_Bulldogs.png",
    "Maine Black Bears": "src/assets/teamLogos/NCAA/Maine_Black_Bears.png",
    "NJIT Highlanders": "src/assets/teamLogos/NCAA/NJIT_Highlanders.png",
    "New Hampshire Wildcats": "src/assets/teamLogos/NCAA/New_Hampshire_Wildcats.png",
    "UAlbany Great Danes": "src/assets/teamLogos/NCAA/Albany_Great_Danes.png",
    "UMBC Retrievers": "src/assets/teamLogos/NCAA/UMBC_Retrievers.png",
    "UMass Lowell River Hawks": "src/assets/teamLogos/NCAA/UMass_Lowell_River_Hawks.png",
    "Vermont Catamounts": "src/assets/teamLogos/NCAA/Vermont_Catamounts.png",

    // American
    "Charlotte 49ers": "src/assets/teamLogos/NCAA/Charlotte_49ers.png",
    "East Carolina Pirates": "src/assets/teamLogos/NCAA/East_Carolina_Pirates.png",
    "Florida Atlantic Owls": "src/assets/teamLogos/NCAA/Florida_Atlantic_Owls.png",
    "North Texas Mean Green": "src/assets/teamLogos/NCAA/North_Texas_Mean_Green.png",
    "Memphis Tigers": "src/assets/teamLogos/NCAA/Memphis_Tigers.png",
    "Rice Owls": "src/assets/teamLogos/NCAA/Rice_Owls.png",
    "South Florida Bulls": "src/assets/teamLogos/NCAA/South_Florida_Bulls.png",
    "Temple Owls": "src/assets/teamLogos/NCAA/Temple_Owls.png",
    "Tulane Green Wave": "src/assets/teamLogos/NCAA/Tulane_Green_Wave.png",
    "Tulsa Golden Hurricane": "src/assets/teamLogos/NCAA/Tulsa_Golden_Hurricane.png",
    "Wichita State Shockers": "src/assets/teamLogos/NCAA/Wichita_State_Shockers.png",
    "UAB Blazers": "src/assets/teamLogos/NCAA/UAB_Blazers.png",
    "UTSA Roadrunners": "src/assets/teamLogos/NCAA/UTSA_Roadrunners.png",

    // A10
    "Davidson Wildcats": "src/assets/teamLogos/NCAA/Davidson_Wildcats.png",
    "Dayton Flyers": "src/assets/teamLogos/NCAA/Dayton_Flyers.png",
    "Duquesne Dukes": "src/assets/teamLogos/NCAA/Duquesne_Dukes.png",
    "Fordham Rams": "src/assets/teamLogos/NCAA/Fordham_Rams.png",
    "George Mason Patriots": "src/assets/teamLogos/NCAA/George_Mason_Patriots.png",
    "George Washington Revolutionaries": "src/assets/teamLogos/NCAA/George_Washington_Revolutionaries.png",
    "La Salle Explorers": "src/assets/teamLogos/NCAA/La_Salle_Explorers.png",
    "Loyola Chicago Ramblers": "src/assets/teamLogos/NCAA/Loyola_Chicago_Ramblers.png",
    "Rhode Island Rams": "src/assets/teamLogos/NCAA/Rhode_Island_Rams.png",
    "Richmond Spiders": "src/assets/teamLogos/NCAA/Richmond_Spiders.png",
    "Saint Joseph's Hawks": "src/assets/teamLogos/NCAA/Saint_Josephs_Hawks.png",
    "Saint Louis Billikens": "src/assets/teamLogos/NCAA/Saint_Louis_Billikens.png",
    "St. Bonaventure Bonnies": "src/assets/teamLogos/NCAA/St_Bonaventure_Bonnies.png",
    "VCU Rams": "src/assets/teamLogos/NCAA/VCU_Rams.png",

    // Big 12
    "Arizona State Sun Devils": "src/assets/teamLogos/NCAA/Arizona_State_Sun_Devils.png",
    "Arizona Wildcats": "src/assets/teamLogos/NCAA/Arizona_Wildcats.png",
    "BYU Cougars": "src/assets/teamLogos/NCAA/BYU_Cougars.png",
    "Baylor Bears": "src/assets/teamLogos/NCAA/Baylor_Bears.png",
    "Cincinnati Bearcats": "src/assets/teamLogos/NCAA/Cincinnati_Bearcats.png",
    "Colorado Buffaloes": "src/assets/teamLogos/NCAA/Colorado_Buffaloes.png",
    "Houston Cougars": "src/assets/teamLogos/NCAA/Houston_Cougars.png",
    "Iowa State Cyclones": "src/assets/teamLogos/NCAA/Iowa_State_Cyclones.png",
    "Kansas Jayhawks": "src/assets/teamLogos/NCAA/Kansas_Jayhawks.png",
    "Kansas State Wildcats": "src/assets/teamLogos/NCAA/Kansas_State_Wildcats.png",
    "Oklahoma State Cowboys": "src/assets/teamLogos/NCAA/Oklahoma_State_Cowboys.png",
    "TCU Horned Frogs": "src/assets/teamLogos/NCAA/TCU_Horned_Frogs.png",
    "Texas Tech Red Raiders": "src/assets/teamLogos/NCAA/Texas_Tech_Red_Raiders.png",
    "UCF Knights": "src/assets/teamLogos/NCAA/UCF_Knights.png",
    "Utah Utes": "src/assets/teamLogos/NCAA/Utah_Utes.png",
    "West Virginia Mountaineers": "src/assets/teamLogos/NCAA/West_Virginia_Mountaineers.png",

    // Big East
    "Butler Bulldogs": "src/assets/teamLogos/NCAA/Butler_Bulldogs.png",
    "Creighton Bluejays": "src/assets/teamLogos/NCAA/Creighton_Bluejays.png",
    "DePaul Blue Demons": "src/assets/teamLogos/NCAA/DePaul_Blue_Demons.png",
    "Georgetown Hoyas": "src/assets/teamLogos/NCAA/Georgetown_Hoyas.png",
    "Marquette Golden Eagles": "src/assets/teamLogos/NCAA/Marquette_Golden_Eagles.png",
    "Providece Friars": "src/assets/teamLogos/NCAA/Providence_Friars.png",
    "Seton Hall Pirates": "src/assets/teamLogos/NCAA/Seton_Hall_Pirates.png",
    "St. John's Red Storm": "src/assets/teamLogos/NCAA/St_Johns_Red_Storm.png",
    "UConn Huskies": "src/assets/teamLogos/NCAA/UConn_Huskies.png",
    "Villanova Wildcats": "src/assets/teamLogos/NCAA/Villanova_Wildcats.png",
    "Xavier Musketeers": "src/assets/teamLogos/NCAA/Xavier_Musketeers.png",

    // Big Sky
    "Eastern Washington Eagles": "src/assets/teamLogos/NCAA/Eastern_Washington_Eagles.png",
    "Idaho Vandals": "src/assets/teamLogos/NCAA/Idaho_Vandals.png",
    "Idaho State Bengals": "src/assets/teamLogos/NCAA/Idaho_State_Bengals.png",
    "Montana Grizzlies": "src/assets/teamLogos/NCAA/Montana_Grizzlies.png",
    "Montana State Bobcats": "src/assets/teamLogos/NCAA/Montana_State_Bobcats.png",
    "Northern Arizona Lumberjacks": "src/assets/teamLogos/NCAA/Northern_Arizona_Lumberjacks.png",
    "Northern Colorado Bears": "src/assets/teamLogos/NCAA/Northern_Colorado_Bears.png",
    "Portland State Vikings": "src/assets/teamLogos/NCAA/Portland_State_Vikings.png",
    "Sacramento State Hornets": "src/assets/teamLogos/NCAA/Sacramento_State_Hornets.png",
    "Weber State Wildcats": "src/assets/teamLogos/NCAA/Weber_State_Wildcats.png",

    // Big South
    "Charleston Southern Buccaneers": "src/assets/teamLogos/NCAA/Charleston_Southern_Buccaneers.png",
    "Gardner-Webb Runnin' Bulldogs": "src/assets/teamLogos/NCAA/Gardner-Webb_Runnin_Bulldogs.png",
    "High Point Panthers": "src/assets/teamLogos/NCAA/High_Point_Panthers.png",
    "Longwood Lancers": "src/assets/teamLogos/NCAA/Longwood_Lancers.png",
    "Presbyterian Blue Hose": "src/assets/teamLogos/NCAA/Presbyterian_Blue_Hose.png",
    "Radford Highlanders": "src/assets/teamLogos/NCAA/Radford_Highlanders.png",
    "South Carolina Upstate Spartans": "src/assets/teamLogos/NCAA/USC_Upstate_Spartans.png",
    "UNC Asheville Bulldogs": "src/assets/teamLogos/NCAA/UNC_Asheville_Bulldogs.png",
    "Winthrop Eagles": "src/assets/teamLogos/NCAA/Winthrop_Eagles.png",

    // Big Ten
    "Illinois Fighting Illini": "src/assets/teamLogos/NCAA/Illinois_Fighting_Illini.png",
    "Indiana Hoosiers": "src/assets/teamLogos/NCAA/Indiana_Hoosiers.png",
    "Iowa Hawkeyes": "src/assets/teamLogos/NCAA/Iowa_Hawkeyes.png",
    "Maryland Terrapins": "src/assets/teamLogos/NCAA/Maryland_Terrapins.png",
    "Michigan Wolverines": "src/assets/teamLogos/NCAA/Michigan_Wolverines.png",
    "Michigan State Spartans": "src/assets/teamLogos/NCAA/Michigan_State_Spartans.png",
    "Minnesota Golden Gophers": "src/assets/teamLogos/NCAA/Minnesota_Golden_Gophers.png",
    "Nebraska Cornhuskers": "src/assets/teamLogos/NCAA/Nebraska_Cornhuskers.png",
    "Northwestern Wildcats": "src/assets/teamLogos/NCAA/Northwestern_Wildcats.png",
    "Ohio State Buckeyes": "src/assets/teamLogos/NCAA/Ohio_State_Buckeyes.png",
    "Oregon Ducks": "src/assets/teamLogos/NCAA/Oregon_Ducks.png",
    "Penn State Nittany Lions": "src/assets/teamLogos/NCAA/Penn_State_Nittany_Lions.png",
    "Purdue Boilermakers": "src/assets/teamLogos/NCAA/Purdue_Boilermakers.png",
    "Rutgers Scarlet Knights": "src/assets/teamLogos/NCAA/Rutgers_Scarlet_Knights.png",
    "UCLA Bruins": "src/assets/teamLogos/NCAA/UCLA_Bruins.png",
    "USC Trojans": "src/assets/teamLogos/NCAA/USC_Trojans.png",
    "Washington Huskies": "src/assets/teamLogos/NCAA/Washington_Huskies.png",
    "Wisconsin Badgers": "src/assets/teamLogos/NCAA/Wisconsin_Badgers.png",

    // Big West
    "Cal Poly Mustangs": "src/assets/teamLogos/NCAA/Cal_Poly_Mustangs.png",
    "Cal State Bakersfield Roadrunners": "src/assets/teamLogos/NCAA/Cal_State_Bakersfield_Roadrunners.png",
    "Cal State Fullerton Titans": "src/assets/teamLogos/NCAA/Cal_State_Fullerton_Titans.png",
    "Cal State Northridge Matadors": "src/assets/teamLogos/NCAA/Cal_State_Northridge_Matadors.png",
    "Hawai'i Rainbow Warriors": "src/assets/teamLogos/NCAA/Hawaii_Rainbow_Warriors.png",
    "Long Beach State Beach": "src/assets/teamLogos/NCAA/Long_Beach_State_Beach.png",
    "UC Davis Aggies": "src/assets/teamLogos/NCAA/UC_Davis_Aggies.png",
    "UC Irvine Anteaters": "src/assets/teamLogos/NCAA/UC_Irvine_Anteaters.png",
    "UC Riverside Highlanders": "src/assets/teamLogos/NCAA/UC_Riverside_Highlanders.png",
    "UC San Diego Tritons": "src/assets/teamLogos/NCAA/UC_San_Diego_Tritons.png",
    "UC Santa Barbara Gauchos": "src/assets/teamLogos/NCAA/UC_Santa_Barbara_Gauchos.png",



    // Coastal
    "Campbell Fighting Camels": "src/assets/teamLogos/NCAA/Campbell_Fighting_Camels.png",
    "Charleston Cougars": "src/assets/teamLogos/NCAA/Charleston_Cougars.png",
    "Drexel Dragons": "src/assets/teamLogos/NCAA/Drexel_Dragons.png",
    "Elon Phoenix": "src/assets/teamLogos/NCAA/Elon_Phoenix.png",
    "Hampton Pirates": "src/assets/teamLogos/NCAA/Hampton_Pirates.png",
    "Hofstra Pride": "src/assets/teamLogos/NCAA/Hofstra_Pride.png",
    "Monmouth Hawks": "src/assets/teamLogos/NCAA/Monmouth_Hawks.png",
    "North Carolina A&T Aggies": "src/assets/teamLogos/NCAA/North_Carolina_AT_Aggies.png",
    "Northeastern Huskies": "src/assets/teamLogos/NCAA/Northeastern_Huskies.png",
    "Stony Brook Seawolves": "src/assets/teamLogos/NCAA/Stony_Brook_Seawolves.png",
    "Towson Tigers": "src/assets/teamLogos/NCAA/Towson_Tigers.png",
    "UNC Wilmington Seahawks": "src/assets/teamLogos/NCAA/UNC_Wilmington_Seahawks.png",
    "William & Mary Tribe": "src/assets/teamLogos/NCAA/William_and_Mary_Tribe.png",

    // Conference USA
    "Delaware Blue Hens": "src/assets/teamLogos/NCAA/Delaware_Blue_Hens.png",
    "Florida International Panthers": "src/assets/teamLogos/NCAA/Florida_International_Panthers.png",
    "Jacksonville State Gamecocks": "src/assets/teamLogos/NCAA/Jacksonville_State_Gamecocks.png",
    "Kennesaw State Owls": "src/assets/teamLogos/NCAA/Kennesaw_State_Owls.png",
    "Liberty Flames": "src/assets/teamLogos/NCAA/Liberty_Flames.png",
    "Louisiana Tech Bulldogs": "src/assets/teamLogos/NCAA/Louisiana_Tech_Bulldogs.png",
    "Middle Tennessee Blue Raiders": "src/assets/teamLogos/NCAA/Middle_Tennessee_Blue_Raiders.png",
    "Missouri State Bears": "src/assets/teamLogos/NCAA/Missouri_State_Bears.png",
    "New Mexico State Aggies": "src/assets/teamLogos/NCAA/New_Mexico_State_Aggies.png",
    "Sam Houston Bearkats": "src/assets/teamLogos/NCAA/Sam_Houston_Bearkats.png",
    "UTEP Miners": "src/assets/teamLogos/NCAA/UTEP_Miners.png",
    "Western Kentucky Hilltoppers": "src/assets/teamLogos/NCAA/Western_Kentucky_Hilltoppers.png",

    // Horizon
    "Cleveland State Vikings": "src/assets/teamLogos/NCAA/Cleveland_State_Vikings.png",
    "Detroit Mercy Titans": "src/assets/teamLogos/NCAA/Detroit_Mercy_Titans.png",
    "Green Bay Phoenix": "src/assets/teamLogos/NCAA/Green_Bay_Phoenix.png",
    "IU Indianapolis Jaguars": "src/assets/teamLogos/NCAA/IU_Indianapolis_Jaguars.png",
    "Milwaukee Panthers": "src/assets/teamLogos/NCAA/Milwaukee_Panthers.png",
    "Northern Kentucky Norse": "src/assets/teamLogos/NCAA/Northern_Kentucky_Norse.png",
    "Oakland Golden Grizzlies": "src/assets/teamLogos/NCAA/Oakland_Golden_Grizzlies.png",
    "Purdue Fort Wayne Mastodons": "src/assets/teamLogos/NCAA/Purdue_Fort_Wayne_Mastodons.png",
    "Robert Morris Colonials": "src/assets/teamLogos/NCAA/Robert_Morris_Colonials.png",
    "Wright State Raiders": "src/assets/teamLogos/NCAA/Wright_State_Raiders.png",
    "Youngstown State Penguins": "src/assets/teamLogos/NCAA/Youngstown_State_Penguins.png",

    // Ivy
    "Brown Bears": "src/assets/teamLogos/NCAA/Brown_Bears.png",
    "Columbia Lions": "src/assets/teamLogos/NCAA/Columbia_Lions.png",
    "Cornell Big Red": "src/assets/teamLogos/NCAA/Cornell_Big_Red.png",
    "Dartmouth Big Green": "src/assets/teamLogos/NCAA/Dartmouth_Big_Green.png",
    "Harvard Crimson": "src/assets/teamLogos/NCAA/Harvard_Crimson.png",
    "Pennsylvania Quakers": "src/assets/teamLogos/NCAA/Pennsylvania_Quakers.png",
    "Princeton Tigers": "src/assets/teamLogos/NCAA/Princeton_Tigers.png",
    "Yale Bulldogs": "src/assets/teamLogos/NCAA/Yale_Bulldogs.png",

    // MAAC
    "Canisius Golden Griffins": "src/assets/teamLogos/NCAA/Canisius_Golden_Griffins.png",
    "Fairfield Stags": "src/assets/teamLogos/NCAA/Fairfield_Stags.png",
    "Iona Gaels": "src/assets/teamLogos/NCAA/Iona_Gaels.png",
    "Manhattan Jaspers": "src/assets/teamLogos/NCAA/Manhattan_Jaspers.png",
    "Marist Red Foxes": "src/assets/teamLogos/NCAA/Marist_Red_Foxes.png",
    "Merrimack Warriors": "src/assets/teamLogos/NCAA/Merrimack_Warriors.png",
    "Mount St. Mary's Mountaineers": "src/assets/teamLogos/NCAA/Mount_St_Marys_Mountaineers.png",
    "Niagara Purple Eagles": "src/assets/teamLogos/NCAA/Niagara_Purple_Eagles.png",
    "Quinnipiac Bobcats": "src/assets/teamLogos/NCAA/Quinnipiac_Bobcats.png",
    "Rider Broncs": "src/assets/teamLogos/NCAA/Rider_Broncs.png",
    "Sacred Heart Pioneers": "src/assets/teamLogos/NCAA/Sacred_Heart_Pioneers.png",
    "Saint Peter's Peacocks": "src/assets/teamLogos/NCAA/Saint_Peters_Peacocks.png",
    "Siena Saints": "src/assets/teamLogos/NCAA/Siena_Saints.png",  

    // MAC
    "Akron Zips": "src/assets/teamLogos/NCAA/Akron_Zips.png",
    "Ball State Cardinals": "src/assets/teamLogos/NCAA/Ball_State_Cardinals.png",
    "Bowling Green Falcons": "src/assets/teamLogos/NCAA/Bowling_Green_Falcons.png",
    "Buffalo Bulls": "src/assets/teamLogos/NCAA/Buffalo_Bulls.png",
    "Central Michigan Chippewas": "src/assets/teamLogos/NCAA/Central_Michigan_Chippewas.png",
    "Eastern Michigan Eagles": "src/assets/teamLogos/NCAA/Eastern_Michigan_Eagles.png",
    "Kent State Golden Flashes": "src/assets/teamLogos/NCAA/Kent_State_Golden_Flashes.png",
    "Massachusetts Minutemen": "src/assets/teamLogos/NCAA/Massachusetts_Minutemen.png",
    "Miami (OH) RedHawks": "src/assets/teamLogos/NCAA/Miami_RedHawks.png",
    "Northern Illinois Huskies": "src/assets/teamLogos/NCAA/Northern_Illinois_Huskies.png",
    "Ohio Bobcats": "src/assets/teamLogos/NCAA/Ohio_Bobcats.png",
    "Toledo Rockets": "src/assets/teamLogos/NCAA/Toledo_Rockets.png",
    "Western Michigan Broncos": "src/assets/teamLogos/NCAA/Western_Michigan_Broncos.png",

    // MEAC
    "Coppin State Eagles": "src/assets/teamLogos/NCAA/Coppin_State_Eagles.png",
    "Delaware State Hornets": "src/assets/teamLogos/NCAA/Delaware_State_Hornets.png",
    "Howard Bison": "src/assets/teamLogos/NCAA/Howard_Bison.png",
    "Maryland Eastern Shore Hawks": "src/assets/teamLogos/NCAA/Maryland_Eastern_Shore_Hawks.png",
    "Morgan State Bears": "src/assets/teamLogos/NCAA/Morgan_State_Bears.png",
    "Norfolk State Spartans": "src/assets/teamLogos/NCAA/Norfolk_State_Spartans.png",
    "North Carolina Central Eagles": "src/assets/teamLogos/NCAA/North_Carolina_Central_Eagles.png",
    "South Carolina State Bulldogs": "src/assets/teamLogos/NCAA/South_Carolina_State_Bulldogs.png",

    // Missouri Valley
    "Belmont Bruins": "src/assets/teamLogos/NCAA/Belmont_Bruins.png",
    "Bradley Braves": "src/assets/teamLogos/NCAA/Bradley_Braves.png",
    "Drake Bulldogs": "src/assets/teamLogos/NCAA/Drake_Bulldogs.png",
    "Evansville Purple Aces": "src/assets/teamLogos/NCAA/Evansville_Purple_Aces.png",
    "Illinois State Redbirds": "src/assets/teamLogos/NCAA/Illinois_State_Redbirds.png",
    "Indiana State Sycamores": "src/assets/teamLogos/NCAA/Indiana_State_Sycamores.png",
    "Murray State Racers": "src/assets/teamLogos/NCAA/Murray_State_Racers.png",
    "Northern Iowa Panthers": "src/assets/teamLogos/NCAA/Northern_Iowa_Panthers.png",
    "Southern Illinois Salukis": "src/assets/teamLogos/NCAA/Southern_Illinois_Salukis.png",
    "UIC Flames": "src/assets/teamLogos/NCAA/UIC_Flames.png",
    "Valparaiso Beacons": "src/assets/teamLogos/NCAA/Valparaiso_Beacons.png",

    // Mountain West
    "Air Force Falcons": "src/assets/teamLogos/NCAA/Air_Force_Falcons.png",
    "Boise State Broncos": "src/assets/teamLogos/NCAA/Boise_State_Broncos.png",
    "Colorado State Rams": "src/assets/teamLogos/NCAA/Colorado_State_Rams.png",
    "Fresno State Bulldogs": "src/assets/teamLogos/NCAA/Fresno_State_Bulldogs.png",
    "Grand Canyon Lopes": "src/assets/teamLogos/NCAA/Grand_Canyon_Lopes.png",
    "Nevada Wolf Pack": "src/assets/teamLogos/NCAA/Nevada_Wolf_Pack.png",
    "New Mexico Lobos": "src/assets/teamLogos/NCAA/New_Mexico_Lobos.png",
    "San Diego State Aztecs": "src/assets/teamLogos/NCAA/San_Diego_State_Aztecs.png",
    "San José State Spartans": "src/assets/teamLogos/NCAA/San_Jose_State_Spartans.png",
    "UNLV Rebels": "src/assets/teamLogos/NCAA/UNLV_Rebels.png",
    "Utah State Aggies": "src/assets/teamLogos/NCAA/Utah_State_Aggies.png",
    "Wyoming Cowboys": "src/assets/teamLogos/NCAA/Wyoming_Cowboys.png",

    // NEC
    "Central Connecticut Blue Devils": "src/assets/teamLogos/NCAA/Central_Connecticut_Blue_Devils.png",
    "Chicago State Cougars": "src/assets/teamLogos/NCAA/Chicago_State_Cougars.png",
    "Fairleigh Dickinson Knights": "src/assets/teamLogos/NCAA/Fairleigh_Dickinson_Knights.png",
    "Le Moyne Dolphins": "src/assets/teamLogos/NCAA/Le_Moyne_Dolphins.png",
    "Long Island University Sharks": "src/assets/teamLogos/NCAA/Long_Island_University_Sharks.png",
    "Mercyhurst Lakers": "src/assets/teamLogos/NCAA/Mercyhurst_Lakers.png",
    "New Haven Chargers": "src/assets/teamLogos/NCAA/New_Haven_Chargers.png",
    "Saint Francis Red Flash": "src/assets/teamLogos/NCAA/Saint_Francis_Red_Flash.png",
    "Stonehill Skyhawks": "src/assets/teamLogos/NCAA/Stonehill_Skyhawks.png",
    "Wagner Seahawks": "src/assets/teamLogos/NCAA/Wagner_Seahawks.png",

    // Ohio Valley
    "Eastern Illinois Panthers": "src/assets/teamLogos/NCAA/Eastern_Illinois_Panthers.png",
    "Lindenwood Lions": "src/assets/teamLogos/NCAA/Lindenwood_Lions.png",
    "Little Rock Trojans": "src/assets/teamLogos/NCAA/Little_Rock_Trojans.png",
    "Morehead State Eagles": "src/assets/teamLogos/NCAA/Morehead_State_Eagles.png",
    "SIU Edwardsville Cougars": "src/assets/teamLogos/NCAA/SIU_Edwardsville_Cougars.png",
    "Southeast Missouri State Redhawks": "src/assets/teamLogos/NCAA/Southeast_Missouri_State_Redhawks.png",
    "Southern Indiana Screaming Eagles": "src/assets/teamLogos/NCAA/Southern_Indiana_Screaming_Eagles.png",
    "Tennessee State Tigers": "src/assets/teamLogos/NCAA/Tennessee_State_Tigers.png",
    "Tennessee Tech Golden Eagles": "src/assets/teamLogos/NCAA/Tennessee_Tech_Golden_Eagles.png",
    "UT Martin Skyhawks": "src/assets/teamLogos/NCAA/UT_Martin_Skyhawks.png",
    "Western Illinois Leathernecks": "src/assets/teamLogos/NCAA/Western_Illinois_Leathernecks.png",

    // Patriot League
    "American University Eagles": "src/assets/teamLogos/NCAA/American_University_Eagles.png",
    "Army Black Knights": "src/assets/teamLogos/NCAA/Army_Black_Knights.png",
    "Boston University Terriers": "src/assets/teamLogos/NCAA/Boston_University_Terriers.png",
    "Bucknell Bison": "src/assets/teamLogos/NCAA/Bucknell_Bison.png",
    "Colgate Raiders": "src/assets/teamLogos/NCAA/Colgate_Raiders.png",
    "Holy Cross Crusaders": "src/assets/teamLogos/NCAA/Holy_Cross_Crusaders.png",
    "Lafayette Leopards": "src/assets/teamLogos/NCAA/Lafayette_Leopards.png",
    "Lehigh Mountain Hawks": "src/assets/teamLogos/NCAA/Lehigh_Mountain_Hawks.png",
    "Loyola Maryland Greyhounds": "src/assets/teamLogos/NCAA/Loyola_Maryland_Greyhounds.png",
    "Navy Midshipmen": "src/assets/teamLogos/NCAA/Navy_Midshipmen.png",

    // SEC
    "Alabama Crimson Tide": "src/assets/teamLogos/NCAA/Alabama_Crimson_Tide.png",
    "Arkansas Razorbacks": "src/assets/teamLogos/NCAA/Arkansas_Razorbacks.png",
    "Auburn Tigers": "src/assets/teamLogos/NCAA/Auburn_Tigers.png",
    "Florida Gators": "src/assets/teamLogos/NCAA/Florida_Gators.png",
    "Georgia Bulldogs": "src/assets/teamLogos/NCAA/Georgia_Bulldogs.png",
    "Kentucky Wildcats": "src/assets/teamLogos/NCAA/Kentucky_Wildcats.png",
    "LSU Tigers": "src/assets/teamLogos/NCAA/LSU_Tigers.png",
    "Mississippi State Bulldogs": "src/assets/teamLogos/NCAA/Mississippi_State_Bulldogs.png",
    "Missouri Tigers": "src/assets/teamLogos/NCAA/Missouri_Tigers.png",
    "Oklahoma Sooners": "src/assets/teamLogos/NCAA/Oklahoma_Sooners.png",
    "Ole Miss Rebels": "src/assets/teamLogos/NCAA/Ole_Miss_Rebels.png",
    "South Carolina Gamecocks": "src/assets/teamLogos/NCAA/South_Carolina_Gamecocks.png",
    "Tennessee Volunteers": "src/assets/teamLogos/NCAA/Tennessee_Volunteers.png",
    "Texas Longhorns": "src/assets/teamLogos/NCAA/Texas_Longhorns.png",
    "Texas A&M Aggies": "src/assets/teamLogos/NCAA/Texas_AM_Aggies.png",
    "Vanderbilt Commodores": "src/assets/teamLogos/NCAA/Vanderbilt_Commodores.png",

    // Southern
    "Chattanooga Mocs": "src/assets/teamLogos/NCAA/Chattanooga_Mocs.png",
    "East Tennessee State Buccaneers": "src/assets/teamLogos/NCAA/East_Tennessee_State_Buccaneers.png",
    "Furman Paladins": "src/assets/teamLogos/NCAA/Furman_Paladins.png",
    "Mercer Bears": "src/assets/teamLogos/NCAA/Mercer_Bears.png",
    "Samford Bulldogs": "src/assets/teamLogos/NCAA/Samford_Bulldogs.png",
    "The Citadel Bulldogs": "src/assets/teamLogos/NCAA/The_Citadel_Bulldogs.png",
    "UNC Greensboro Spartans": "src/assets/teamLogos/NCAA/UNC_Greensboro_Spartans.png",
    "VMI Keydets": "src/assets/teamLogos/NCAA/VMI_Keydets.png",
    "Western Carolina Catamounts": "src/assets/teamLogos/NCAA/Western_Carolina_Catamounts.png",
    "Wofford Terriers": "src/assets/teamLogos/NCAA/Wofford_Terriers.png",

    // Southland
    "East Texas A&M Lions": "src/assets/teamLogos/NCAA/East_Texas_AM_Lions.png",
    "Houston Christian Huskies": "src/assets/teamLogos/NCAA/Houston_Christian_Huskies.png",
    "Incarnate Word Cardinals": "src/assets/teamLogos/NCAA/Incarnate_Word_Cardinals.png",
    "McNeese Cowboys": "src/assets/teamLogos/NCAA/McNeese_Cowboys.png",
    "New Orleans Privateers": "src/assets/teamLogos/NCAA/New_Orleans_Privateers.png",
    "Nicholls Colonels": "src/assets/teamLogos/NCAA/Nicholls_Colonels.png",
    "Northwestern State Demons": "src/assets/teamLogos/NCAA/Northwestern_State_Demons.png",
    "SE Louisiana Lions": "src/assets/teamLogos/NCAA/SE_Louisiana_Lions.png",
    "Stephen F. Austin Lumberjacks": "src/assets/teamLogos/NCAA/Stephen_F_Austin_Lumberjacks.png",
    "Texas A&M-Corpus Christi Islanders": "src/assets/teamLogos/NCAA/Texas_AM_Corpus_Christi_Islanders.png",
    "UT Rio Grande Valley Vaqueros": "src/assets/teamLogos/NCAA/UT_Rio_Grande_Valley_Vaqueros.png", 

    // summit
    "Denver Pioneers": "src/assets/teamLogos/NCAA/Denver_Pioneers.png",
    "Kansas City Roos": "src/assets/teamLogos/NCAA/Kansas_City_Roos.png",
    "North Dakota Fighting Hawks": "src/assets/teamLogos/NCAA/North_Dakota_Fighting_Hawks.png",
    "North Dakota State Bison": "src/assets/teamLogos/NCAA/North_Dakota_State_Bison.png",
    "Omaha Mavericks": "src/assets/teamLogos/NCAA/Omaha_Mavericks.png",
    "Oral Roberts Golden Eagles": "src/assets/teamLogos/NCAA/Oral_Roberts_Golden_Eagles.png",
    "South Dakota Coyotes": "src/assets/teamLogos/NCAA/South_Dakota_Coyotes.png",
    "South Dakota State Jackrabbits": "src/assets/teamLogos/NCAA/South_Dakota_State_Jackrabbits.png",
    "St. Thomas-Minnesota Tommies": "src/assets/teamLogos/NCAA/St_Thomas-Minnesota_Tommies.png",


    // Sun Belt
    "App State Mountaineers": "src/assets/teamLogos/NCAA/App_State_Mountaineers.png",
    "Arkansas State Red Wolves": "src/assets/teamLogos/NCAA/Arkansas_State_Red_Wolves.png",
    "Coastal Carolina Chanticleers": "src/assets/teamLogos/NCAA/Coastal_Carolina_Chanticleers.png",
    "Georgia Southern Eagles": "src/assets/teamLogos/NCAA/Georgia_Southern_Eagles.png",
    "Georgia State Panthers": "src/assets/teamLogos/NCAA/Georgia_State_Panthers.png",
    "James Madison Dukes": "src/assets/teamLogos/NCAA/James_Madison_Dukes.png",
    "Louisiana Ragin' Cajuns": "src/assets/teamLogos/NCAA/Louisiana_Ragin_Cajuns.png",
    "UL Monroe Warhawks": "src/assets/teamLogos/NCAA/UL_Monroe_Warhawks.png",
    "Marshall Thundering Herd": "src/assets/teamLogos/NCAA/Marshall_Thundering_Herd.png",
    "Old Dominion Monarchs": "src/assets/teamLogos/NCAA/Old_Dominion_Monarchs.png",
    "South Alabama Jaguars": "src/assets/teamLogos/NCAA/South_Alabama_Jaguars.png",
    "Southern Miss Golden Eagles": "src/assets/teamLogos/NCAA/Southern_Miss_Golden_Eagles.png",
    "Texas State Bobcats": "src/assets/teamLogos/NCAA/Texas_State_Bobcats.png",
    "Troy Trojans": "src/assets/teamLogos/NCAA/Troy_Trojans.png",

    // SWAC
    "Alabama A&M Bulldogs": "src/assets/teamLogos/NCAA/Alabama_AM_Bulldogs.png",
    "Alabama State Hornets": "src/assets/teamLogos/NCAA/Alabama_State_Hornets.png",
    "Alcorn State Braves": "src/assets/teamLogos/NCAA/Alcorn_State_Braves.png",
    "Arkansas-Pine Bluff Golden Lions": "src/assets/teamLogos/NCAA/Arkansas-Pine_Bluff_Golden_Lions.png",
    "Bethune-Cookman Wildcats": "src/assets/teamLogos/NCAA/Bethune-Cookman_Wildcats.png",
    "Florida A&M Rattlers": "src/assets/teamLogos/NCAA/Florida_AM_Rattlers.png",
    "Grambling Tigers": "src/assets/teamLogos/NCAA/Grambling_Tigers.png",
    "Jackson State Tigers": "src/assets/teamLogos/NCAA/Jackson_State_Tigers.png",
    "Mississippi Valley State Delta Devils": "src/assets/teamLogos/NCAA/Mississippi_Valley_State_Delta_Devils.png",
    "Prairie View A&M Panthers": "src/assets/teamLogos/NCAA/Prairie_View_AM_Panthers.png",
    "Southern Jaguars": "src/assets/teamLogos/NCAA/Southern_Jaguars.png",
    "Texas Southern Tigers": "src/assets/teamLogos/NCAA/Texas_Southern_Tigers.png",

    // WAC
    "Abilene Christian Wildcats": "src/assets/teamLogos/NCAA/Abilene_Christian_Wildcats.png",
    "California Baptist Lancers": "src/assets/teamLogos/NCAA/California_Baptist_Lancers.png",
    "Southern Utah Thunderbirds": "src/assets/teamLogos/NCAA/Southern_Utah_Thunderbirds.png",
    "Tarleton State Texans": "src/assets/teamLogos/NCAA/Tarleton_State_Texans.png",
    "UT Arlington Mavericks": "src/assets/teamLogos/NCAA/UT_Arlington_Mavericks.png",
    "Utah Tech Trailblazers": "src/assets/teamLogos/NCAA/Utah_Tech_Trailblazers.png",
    "Utah Valley Wolverines": "src/assets/teamLogos/NCAA/Utah_Valley_Wolverines.png",

    // WCC
    "Gonzaga Bulldogs": "src/assets/teamLogos/NCAA/Gonzaga_Bulldogs.png",
    "Loyola Marymount Lions": "src/assets/teamLogos/NCAA/Loyola_Marymount_Lions.png",
    "Oregon State Beavers": "src/assets/teamLogos/NCAA/Oregon_State_Beavers.png",
    "Pacific Tigers": "src/assets/teamLogos/NCAA/Pacific_Tigers.png",
    "Pepperdine Waves": "src/assets/teamLogos/NCAA/Pepperdine_Waves.png",
    "Portland Pilots": "src/assets/teamLogos/NCAA/Portland_Pilots.png",
    "San Francisco Dons": "src/assets/teamLogos/NCAA/San_Francisco_Dons.png",
    "Santa Clara Broncos": "src/assets/teamLogos/NCAA/Santa_Clara_Broncos.png",
    "San Diego Toreros": "src/assets/teamLogos/NCAA/San_Diego_Toreros.png",
    "Saint Mary's Gaels": "src/assets/teamLogos/NCAA/Saint_Marys_Gaels.png",
    "Seattle U Redhawks": "src/assets/teamLogos/NCAA/Seattle_U_Redhawks.png",
    "Washington State Cougars": "src/assets/teamLogos/NCAA/Washington_State_Cougars.png",
}

export function abbr(name) {
    return teamAbbreviations[name] || name;
}

export function logo(name) {
    return teamLogos[name] || null;
}