def fullNameNCAA(name):
    fullNames = {

        # America East
        "Albany": "Albany Great Danes",
        "Binghamton": "Binghamton Bearcats",
        "Bryant": "Bryant Bulldogs",
        "Maine": "Maine Black Bears",
        "New Hampshire": "New Hampshire Wildcats",
        "NJIT": "NJIT Highlanders",
        "UMBC": "UMBC Retrievers",
        "UMass Lowell": "UMass Lowell River Hawks",
        "Vermont": "Vermont Catamounts",

        # American
        "Charlotte": "Charlotte 49ers",
        "East Carolina": "East Carolina Pirates",
        "Florida Atlantic": "Florida Atlantic Owls",
        "Memphis": "Memphis Tigers",
        "North Texas": "North Texas Mean Green",
        "Rice": "Rice Owls",
        "South Florida": "South Florida Bulls",
        "Temple": "Temple Owls",
        "Tulane": "Tulane Green Wave",
        "Tulsa": "Tulsa Golden Hurricane",
        "UAB": "UAB Blazers",
        "UTSA": "UTSA Roadrunners",
        "Wichita State": "Wichita State Shockers",

        # ACC
        "Boston College": "Boston College Eagles",
        "California": "California Golden Bears",
        "Clemson": "Clemson Tigers",
        "Duke": "Duke Blue Devils",
        "Florida State": "Florida State Seminoles",
        "Georgia Tech": "Georgia Tech Yellow Jackets",
        "Louisville": "Louisville Cardinals",
        "Miami (FL)": "Miami Hurricanes",
        "NC State": "NC State Wolfpack",
        "North Carolina": "North Carolina Tar Heels",
        "Notre Dame": "Notre Dame Fighting Irish",
        "Pittsburgh": "Pittsburgh Panthers",
        "Southern Methodist": "SMU Mustangs",
        "Stanford": "Stanford Cardinal",
        "Syracuse": "Syracuse Orange",
        "Virginia": "Virginia Cavaliers",
        "Virginia Tech": "Virginia Tech Hokies",
        "Wake Forest": "Wake Forest Demon Deacons",

        # ASUN
        "Austin Peay": "Austin Peay Governors",
        "Bellarmine": "Bellarmine Knights",
        "Central Arkansas": "Central Arkansas Bears",
        "Eastern Kentucky": "Eastern Kentucky Colonels",
        "FGCU": "Florida Gulf Coast Eagles",
        "Jacksonville": "Jacksonville Dolphins",
        "Lipscomb": "Lipscomb Bisons",
        "North Alabama": "North Alabama Lions",
        "North Florida": "North Florida Ospreys",
        "Queens Royals": "Queens University Royals",
        "Stetson": "Stetson Hatters",
        "West Georgia": "West Georgia Wolves",

        # Atlantic 10
        "Dayton": "Dayton Flyers",
        "Davidson": "Davidson Wildcats",
        "Duquesne": "Duquesne Dukes",
        "Fordham": "Fordham Rams",
        "George Mason": "George Mason Patriots",
        "George Washington": "George Washington Revolutionaries",
        "La Salle": "La Salle Explorers",
        "Loyola Chicago": "Loyola Chicago Ramblers",
        "Rhode Island": "Rhode Island Rams",
        "Richmond": "Richmond Spiders",
        "Saint Joseph's": "Saint Joseph's Hawks",
        "Saint Louis": "Saint Louis Billikens",
        "St. Bonaventure": "St. Bonaventure Bonnies",
        "VCU": "VCU Rams",

        # Big 12
        "Arizona": "Arizona Wildcats",
        "Arizona State": "Arizona State Sun Devils",
        "BYU": "BYU Cougars",
        "Brigham Young": "BYU Cougars",
        "Baylor": "Baylor Bears",
        "Cincinnati": "Cincinnati Bearcats",
        "Colorado": "Colorado Buffaloes",
        "Houston": "Houston Cougars",
        "Iowa State": "Iowa State Cyclones",
        "Kansas": "Kansas Jayhawks",
        "Kansas State": "Kansas State Wildcats",
        "Oklahoma State": "Oklahoma State Cowboys",
        "TCU": "TCU Horned Frogs",
        "Texas Tech": "Texas Tech Red Raiders",
        "West Virginia": "West Virginia Mountaineers",
        "Utah": "Utah Utes",
        "UCF": "UCF Knights",

        # Big East Conference
        "Butler": "Butler Bulldogs",
        "Creighton": "Creighton Bluejays",
        "DePaul": "DePaul Blue Demons",
        "Georgetown": "Georgetown Hoyas",
        "Marquette": "Marquette Golden Eagles",
        "Providence": "Providence Friars",
        "Seton Hall": "Seton Hall Pirates",
        "St. John's (N.Y.)": "St. John's Red Storm",
        "UConn": "UConn Huskies",
        "Connecticut": "UConn Huskies",
        "Villanova": "Villanova Wildcats",
        "Xavier": "Xavier Musketeers",

        # Big Sky
        "East. Washington": "Eastern Washington Eagles",
        "Idaho State": "Idaho State Bengals",
        "Idaho": "Idaho Vandals",
        "Montana": "Montana Grizzlies",
        "Montana State": "Montana State Bobcats",
        "Northern Arizona": "Northern Arizona Lumberjacks",
        "Northern Colorado": "Northern Colorado Bears",
        "Portland State": "Portland State Vikings",
        "Sacramento State": "Sacramento State Hornets",
        "Weber State": "Weber State Wildcats",

        # Big South
        "Charleston Southern": "Charleston Southern Buccaneers",
        "Gardner Webb": "Gardner-Webb Runnin' Bulldogs",
        "High Point": "High Point Panthers",
        "Longwood": "Longwood Lancers",
        "Presbyterian": "Presbyterian Blue Hose",
        "Radford": "Radford Highlanders",
        "USC Upstate": "South Carolina Upstate Spartans",
        "UNC Asheville": "UNC Asheville Bulldogs",
        "Winthrop": "Winthrop Eagles",

        # Big Ten
        "Illinois": "Illinois Fighting Illini",
        "Indiana": "Indiana Hoosiers",
        "Iowa": "Iowa Hawkeyes",
        "Maryland": "Maryland Terrapins",
        "Michigan": "Michigan Wolverines",
        "Michigan State": "Michigan State Spartans",
        "Minnesota": "Minnesota Golden Gophers",
        "Nebraska": "Nebraska Cornhuskers",
        "Northwestern": "Northwestern Wildcats",
        "Ohio State": "Ohio State Buckeyes",
        "Oregon": "Oregon Ducks",
        "Penn State": "Penn State Nittany Lions",
        "Purdue": "Purdue Boilermakers",
        "Rutgers": "Rutgers Scarlet Knights",
        "UCLA": "UCLA Bruins",
        "USC": "USC Trojans",
        "Washington": "Washington Huskies",
        "Wisconsin": "Wisconsin Badgers",

        # Big West
        "Cal Poly": "Cal Poly Mustangs",
        "CSU Bakersfield": "Cal State Bakersfield Roadrunners",
        "CS Fullerton": "Cal State Fullerton Titans",
        "CS Northridge": "Cal State Northridge Matadors",
        "Hawaii": "Hawai'i Rainbow Warriors",
        "Long Beach State": "Long Beach State Beach",
        "UC Davis": "UC Davis Aggies",
        "UC Irvine": "UC Irvine Anteaters",
        "UC Riverside": "UC Riverside Highlanders",
        "UC San Diego": "UC San Diego Tritons",
        "UC Santa Barbara": "UC Santa Barbara Gauchos",

        # Coastal
        "Campbell": "Campbell Fighting Camels",
        "Charleston": "Charleston Cougars",
        "Drexel": "Drexel Dragons",
        "Elon": "Elon Phoenix",
        "Hampton": "Hampton Pirates",
        "Hofstra": "Hofstra Pride",
        "Monmouth": "Monmouth Hawks",
        "N. Carolina A&T": "North Carolina A&T Aggies",
        "Stony Brook": "Stony Brook Seawolves",
        "Towson": "Towson Tigers",
        "NC Wilmington": "UNC Wilmington Seahawks",
        "William & Mary": "William & Mary Tribe",


        # Conference USA
        "Delaware": "Delaware Blue Hens",
        "Delaware Fightin": "Delaware Blue Hens",
        "Jacksonville State": "Jacksonville State Gamecocks",
        "Liberty": "Liberty Flames",
        "Louisiana Tech": "Louisiana Tech Bulldogs",
        "Middle Tenn. St.": "Middle Tennessee Blue Raiders",
        "Missouri State": "Missouri State Bears",
        "Sam Houston": "Sam Houston Bearkats",
        "Western Kentucky": "Western Kentucky Hilltoppers",

        # Horizon
        "Cleveland State": "Cleveland State Vikings",
        "Detroit": "Detroit Mercy Titans",
        "IU Indy": "IU Indianapolis Jaguars",
        "Oakland": "Oakland Golden Grizzlies",
        "IPFW": "Purdue Fort Wayne Mastodons",
        "Robert Morris": "Robert Morris Colonials",
        "Wisc. Green Bay": "Green Bay Phoenix",
        "Wisc. Milwaukee": "Milwaukee Panthers",
        "Wright State": "Wright State Raiders",
        "Youngstown State": "Youngstown State Penguins",

        # Ivy League
        "Harvard": "Harvard Crimson",
        "Yale": "Yale Bulldogs",
        "Princeton": "Princeton Tigers",
        "Penn": "Pennsylvania Quakers",
        "Cornell": "Cornell Big Red",
        "Dartmouth": "Dartmouth Big Green",
        "Brown": "Brown Bears",
        "Columbia": "Columbia Lions",

        # MAAC
        "Canisius": "Canisius Golden Griffins",
        "Fairfield": "Fairfield Stags",
        "Iona": "Iona Gaels",
        "Manhattan": "Manhattan Jaspers",
        "Marist": "Marist Red Foxes",
        "Merrimack": "Merrimack Warriors",
        "Mount St. Mary's": "Mount St. Mary's Mountaineers",
        "Niagara": "Niagara Purple Eagles",
        "Quinnipiac": "Quinnipiac Bobcats",
        "Rider": "Rider Broncs",
        "Sacred Heart": "Sacred Heart Pioneers",
        "St. Peters": "Saint Peter's Peacocks",
        "Siena": "Siena Saints",

        # MEAC
        "Coppin State": "Coppin State Eagles",
        "Delaware State": "Delaware State Hornets",
        "Howard": "Howard Bison",
        "Md.-East. Shore": "Maryland Eastern Shore Hawks",
        "Morgan State": "Morgan State Bears",
        "Norfolk State": "Norfolk State Spartans",
        "N. Carolina Central": "North Carolina Central Eagles",
        "South Carolina State": "South Carolina State Bulldogs",

        # Mid-American
        "Akron": "Akron Zips",
        "Ball State": "Ball State Cardinals",
        "Bowling Green": "Bowling Green Falcons",
        "Buffalo": "Buffalo Bulls",
        "Central Michigan": "Central Michigan Chippewas",
        "Eastern Michigan": "Eastern Michigan Eagles",
        "Kent State": "Kent State Golden Flashes",
        "Miami (Ohio)": "Miami RedHawks",
        "Miami (Oh)": "Miami RedHawks",
        "Northern Illinois": "Northern Illinois Huskies",
        "Ohio": "Ohio Bobcats",
        "Toledo": "Toledo Rockets",
        "Western Michigan": "Western Michigan Broncos",
        "UMass": "Massachusetts Minutemen",

        # Missouri Valley
        "Belmont": "Belmont Bruins",
        "Bradley": "Bradley Braves",
        "Drake": "Drake Bulldogs",
        "Evansville": "Evansville Purple Aces",
        "Illinois (Chi.)": "UIC Flames",
        "Illinois State": "Illinois State Redbirds",
        "Indiana State": "Indiana State Sycamores",
        "Murray State": "Murray State Racers",
        "Northern Iowa": "Northern Iowa Panthers",
        "Southern Illinois": "Southern Illinois Salukis",
        "Valparaiso": "Valparaiso Beacons",

        # Mountain West
        "Air Force": "Air Force Falcons",
        "Boise State": "Boise State Broncos",
        "Colorado State": "Colorado State Rams",
        "Fresno State": "Fresno State Bulldogs",
        "Grand Canyon": "Grand Canyon Lopes",
        "Nevada": "Nevada Wolf Pack",
        "New Mexico": "New Mexico Lobos",
        "San Diego State": "San Diego State Aztecs",
        "San Jose State": "San Jose State Spartans",
        "UNLV": "UNLV Rebels",
        "Utah State": "Utah State Aggies",
        "Wyoming": "Wyoming Cowboys",

        # NEC
        "Central Connecticut": "Central Connecticut Blue Devils",
        "Chicago State": "Chicago State Cougars",
        "Fairleigh Dickinson": "Fairleigh Dickinson Knights",
        "Le Moyne": "Le Moyne Dolphins",
        "LIU Sharks": "Long Island University Sharks",
        "Mercyhurst": "Mercyhurst Lakers",
        "Mount St. Mary's": "Mount St. Mary's Mountaineers",
        "New Haven": "New Haven Chargers",
        "Saint Francis": "Saint Francis Red Flash",
        "Stonehill": "Stonehill Skyhawks",
        "Wagner": "Wagner Seahawks",


        # Ohio Valley
        "Eastern Illinois": "Eastern Illinois Panthers",
        "Lindenwood": "Lindenwood Lions",
        "UALR": "Little Rock Trojans",
        "Morehead State": "Morehead State Eagles",
        "Siu Edwardsville": "SIU Edwardsville Cougars",
        "Southern Indiana": "Southern Indiana Screaming Eagles",
        "Tennessee State": "Tennessee State Tigers",
        "Tennessee Tech": "Tennessee Tech Golden Eagles",
        "UT Martin": "UT Martin Skyhawks",
        "Western Illinois": "Western Illinois Leathernecks",

        # Patriot League
        "American University": "American University Eagles",
        "Army": "Army Black Knights",
        "Boston University": "Boston University Terriers",
        "Bucknell": "Bucknell Bison",
        "Colgate": "Colgate Raiders",
        "Holy Cross": "Holy Cross Crusaders",
        "Lafayette": "Lafayette Leopards",
        "Lehigh": "Lehigh Mountain Hawks",
        "Loyola Maryland": "Loyola Maryland Greyhounds",
        "Navy": "Navy Midshipmen",

        # SEC
        "Alabama": "Alabama Crimson Tide",
        "Arkansas": "Arkansas Razorbacks",
        "Auburn": "Auburn Tigers",
        "Florida": "Florida Gators",
        "Georgia": "Georgia Bulldogs",
        "Kentucky": "Kentucky Wildcats",
        "LSU": "LSU Tigers",
        "Mississippi St.": "Mississippi State Bulldogs",
        "Missouri": "Missouri Tigers",
        "Oklahoma": "Oklahoma Sooners",
        "Ole Miss": "Ole Miss Rebels",
        "South Carolina": "South Carolina Gamecocks",
        "Tennessee": "Tennessee Volunteers",
        "Texas": "Texas Longhorns",
        "Texas A&M": "Texas A&M Aggies",
        "Vanderbilt": "Vanderbilt Commodores",

        # Southern
        "Chattanooga": "Chattanooga Mocs",
        "East Tennessee St": "East Tennessee State Buccaneers",
        "East Tennessee State": "East Tennessee State Buccaneers",
        "Furman": "Furman Paladins",
        "Mercer": "Mercer Bears",
        "Samford": "Samford Bulldogs",
        "Citadel": "The Citadel Bulldogs",
        "NC Greensboro": "UNC Greensboro Spartans",
        "UNC Greensboro": "UNC Greensboro Spartans",
        "VMI": "VMI Keydets",
        "Western Carolina": "Western Carolina Catamounts",
        "Wofford": "Wofford Terriers",

        # Southland
        "East Texas A&M": "East Texas A&M Lions",
        "Houston Christian": "Houston Christian Huskies",
        "Incarnate Word": "Incarnate Word Cardinals",
        "Lamar": "Lamar Cardinals",
        "McNeese": "McNeese State Cowboys",
        "McNeese State": "McNeese State Cowboys",
        "New Orleans": "New Orleans Privateers",
        "Nicholls": "Nicholls Colonels",
        "Nicholls State": "Nicholls Colonels",
        "Northwestern State": "Northwestern State Demons",
        "Northwestern St.": "Northwestern State Demons",
        "Southeastern Louisiana": "SE Louisiana Lions",
        "SE Louisiana": "SE Louisiana Lions",
        "Stephen F. Austin": "Stephen F. Austin Lumberjacks",
        "Texas A&M-CC": "Texas A&M-Corpus Christi Islanders",
        "UTRGV": "UT Rio Grande Valley Vaqueros",

        # Summit
        "Denver": "Denver Pioneers",
        "UMKC": "Kansas City Roos",
        "Nebraska O.": "Omaha Mavericks",
        "North Dakota": "North Dakota Fighting Hawks",
        "North Dakota St": "North Dakota State Bison",
        "Oral Roberts": "Oral Roberts Golden Eagles",
        "St. Thomas (Minn.)": "St. Thomas-Minnesota Tommies",
        "South Dakota": "South Dakota Coyotes",
        "South Dakota St.": "South Dakota State Jackrabbits",

        # Sun Belt
        "Appalachian State": "App State Mountaineers",
        "Arkansas State": "Arkansas State Red Wolves",
        "Coastal Carolina": "Coastal Carolina Chanticleers",
        "Georgia Southern": "Georgia Southern Eagles",
        "Georgia State": "Georgia State Panthers",
        "James Madison": "James Madison Dukes",
        "Louisiana Lafayette": "Louisiana Ragin' Cajuns",
        "Louisiana Monroe": "Louisiana-Monroe Warhawks",
        "Marshall": "Marshall Thundering Herd",
        "Old Dominion": "Old Dominion Monarchs",
        "South Alabama": "South Alabama Jaguars",
        "Southern Miss": "Southern Miss Golden Eagles",
        "Texas State": "Texas State Bobcats",
        "Troy": "Troy Trojans",


        # SWAC
        "Alabama A&M": "Alabama A&M Bulldogs",
        "Alabama State": "Alabama State Hornets",
        "Alcorn State": "Alcorn State Braves",
        "Arkansas-Pine Bluff": "Arkansas-Pine Bluff Golden Lions",
        "Bethune-Cookman": "Bethune-Cookman Wildcats",
        "Florida A&M": "Florida A&M Rattlers",
        "Grambling St.": "Grambling Tigers",
        "Grambling State": "Grambling Tigers",
        "Miss. Valley St.": "Mississippi Valley State Delta Devils",
        "Prairie V.": "Prairie View A&M Panthers",
        "Prairie View A&M": "Prairie View A&M Panthers",
        "Southern Univ.": "Southern Jaguars",
        "Texas Southern": "Texas Southern Tigers",

        # WAC
        "Abilene Christian": "Abilene Christian Wildcats",
        "California Baptist": "California Baptist Lancers",
        "Southern Utah": "Southern Utah Thunderbirds",
        "Tarleton": "Tarleton State Texans",
        "UT Arlington": "UT Arlington Mavericks",
        "Utah Tech": "Utah Tech Trailblazers",
        "Utah Valley State": "Utah Valley Wolverines",

        # West Coast Conference
        "Gonzaga": "Gonzaga Bulldogs",
        "Loyola Marymount": "Loyola Marymount Lions",
        "Pacific": "Pacific Tigers",
        "Pepperdine": "Pepperdine Waves",
        "Portland": "Portland Pilots",
        "San Diego": "San Diego Toreros",
        "San Francisco": "San Francisco Dons",
        "Santa Clara": "Santa Clara Broncos",
        "Seattle": "Seattle Redhawks",
        "St. Marys (CA)": "Saint Mary's Gaels",
    }
    return fullNames.get(name, name)
    
def fullNameSoccer(name):
    fullNames = {

        # international
        "Côte d'Ivoire": "Ivory Coast",

        # England
        "Birmingham": "Birmingham City",
        "Blackburn": "Blackburn Rovers",
        "Bournemouth": "AFC Bournemouth",
        "Brighton": "Brighton & Hove Albion",
        "Coventry": "Coventry City",
        "Derby": "Derby County",
        "Hull": "Hull City",
        "Ipswich": "Ipswich Town",
        "Leeds": "Leeds United",
        "Leicester": "Leicester City",
        "Man City": "Manchester City",
        "Man Utd": "Manchester United",
        "Newcastle": "Newcastle United",
        "Norwich": "Norwich City",
        "Nottm Forest": "Nottingham Forest",
        "Oxford": "Oxford United",
        "Preston": "Preston North End",
        "QPR": "Queens Park Rangers",
        "Sheff Utd": "Sheffield United",
        "Sheff Wed": "Sheffield Wednesday",
        "Spurs": "Tottenham Hotspur",
        "Stoke": "Stoke City",
        "Swansea": "Swansea City",
        "West Bromwich": "West Bromwich Albion",
        "West Ham": "West Ham United",
        "Wolves": "Wolverhampton Wanderers",
    }
    return fullNames.get(name, name)